using System.Collections.Generic;

namespace playlist2csv
{
    /// <summary>
    /// Structure to represent a DTD PLIST play list as generated by the DJM-REC app for Apple iPads and iPhones.  
    /// </summary>
    internal class PlayList
    {
        /// <summary>
        /// The trackes recorded in the play list.
        /// </summary>
        private List<Track> tracks;

        /// <summary>
        /// The sample rate in hertz. Used to convert the integer time stamp value contained in each track to an elapsed time value.
        /// For example if the sample rate is 48000 and the time stamp is 120000 then we can deduce that 2.5 seconds has elapsed since
        /// the start of the set. 
        /// </summary>
        private double samplerate;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="tracks">The list of tracks.</param>
        /// <param name="samplerate">The sample rate</param>
        public PlayList (List<Track> tracks, double samplerate)
        {
            this.tracks = tracks;   
            this.samplerate = samplerate;
        }


        /// <summary>
        /// Gets the tracks in this play list.
        /// </summary>
        public List<Track> Tracks
        { 
            get 
            { 
                return tracks; 
            } 
        }      

        /// <summary>
        /// Gets the sample rate of the recording. 
        /// </summary>
        public double SampleRate
        { 
            get 
            {
                return samplerate; 
            } 
        }  
    }
}
